[package]
name = "myps"
version = "0.1.0"
edition = "2018"

[dependencies]
ast-traits = { path = "../ast-traits" }
mips = { path = "../mips" }
maplit = "*"
itertools = "*"
pest = "*"
pest_derive = "*"
serde = "*"
ron = "*"
lazy_static = "*"


