[workspace]
members = [
    "./ast-traits",
    # "./ast-common",
    "./mips",
    "./myps",
    "./translator",
    "./app",
]

[profile.release]
lto = true

# [target."cfg(debug_assertions)".dependencies]
# console_error_panic_hook = "*"
