[package]
name = "mips"
version = "0.1.0"
edition = "2018"

[dependencies]
ast-traits = { path = "../ast-traits" }
# ast-common = { path = "../ast-common" }
maplit = "*"
itertools = "*"
pest = "*"
pest_derive = "*"
serde = "*"
ron = "*"

